[project]
name = "z-photos"
version = "0.1.0"
description = "Zalo Photos Assignment 2026"
readme = "README.md"
requires-python = ">=3.13"
authors = [{ name = "Kỳ", email = "40734986+itskyf@users.noreply.github.com" }]
dependencies = [
  "accelerate~=1.13",
  "dagshub~=0.6",
  "datasets~=4.7",
  "fiftyone~=1.13",
  "mlflow~=3.10",
  "torch~=2.10",
  "torchmetrics~=1.9",
  "transformers~=5.3",
]

[dependency-groups]
dev = [
  "ipykernel~=7.2",
  "ipywidgets~=8.1",
]

[build-system]
requires = ["hatch-vcs", "hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"
fallback-version = "0.0.0"
