fix = true

[lint]
select = [
  "B",  # flake8-bugbear
  "C4",  # flake8-comprehensions
  "E",  # pycodestyle
  "F",  # Pyflakes
  "FURB",  # refurb
  "G",  # flake8-logging-format
  "I",  # isort
  "N",  # pep8-naming
  "NPY",  # NumPy
  "PERF",  # Perflint
  "RUF",  # Ruff
  "SIM",  # flake8-simplify
  "TC",  # flake8-type-checking
  "TID",  # flake8-tidy-imports
  "TRY",  # tryceratops
  "UP",  # pyupgrade
  "W",  # pycodestyle
]
ignore = ["TRY003"]

[lint.pydocstyle]
convention = "google"
